name: Parallel Hello

on: [push]

jobs:
  Test-suite-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello from Job 1!"

  Test-suite-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello from Job 2!"

  Test-suite-3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello from Job 3!"

  dev-deploy:
    runs-on: ubuntu-latest
    needs: [Test-suite-1,Test-suite-2, Test-suite-3]
    steps:
      - run: echo "✅ All jobs finished, Hello from Final Job!"
